apiVersion: v1
kind: Service
metadata:
  name: testserver
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
    service.beta.kubernetes.io/vultr-loadbalancer-backend-protocol: "tcp"
spec:
  selector:
    app: testserver
  ports:
    - protocol: TCP
      name: "80"
      port: 80
    - protocol: TCP
      name: "443"
      port: 443
    - protocol: TCP
      name: "8000"
      port: 8000
    - protocol: TCP
      name: "8080"
      port: 8080
    - protocol: TCP
      name: "8443"
      port: 8443
  type: LoadBalancer